# Site settings
title: Justyna Ratajczak | WordPress Developer
email: justyna.ratajczak@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm an independent WordPress developer. I help agencies and freelancers keep their clients happy by providing the best solutions WordPress has to offer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hellojusi.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hellojusi
github_username:  hellojusi

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude: ["_dev",
          "gulpfile.js",
          "node_modules",
          "package.json",
          "CNAME"]